// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"be-golang-chapter-26/LA-Chapter-26B/greeter"
	"be-golang-chapter-26/LA-Chapter-26B/service"
)

// Injectors from wire.go:

func InitializMyService() *service.Service {
	greeterGreeter := greeter.NewGreeter()
	serviceService := service.NewService(greeterGreeter)
	return serviceService
}
