// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"be-golang-chapter-26/Restfull-API-DI/database"
	"be-golang-chapter-26/Restfull-API-DI/handler"
	"be-golang-chapter-26/Restfull-API-DI/repository"
	"be-golang-chapter-26/Restfull-API-DI/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializProductHandler() *handler.ProductHandler {
	db := database.NewPostgresDB()
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	return productHandler
}

// wire.go:

var productHandlerSet = wire.NewSet(database.NewPostgresDB, repository.NewProductRepository, service.NewProductService, handler.NewProductHandler)
